##
# 80 Characters allows codebases to be more easily read in split screen mode,
# as well as on other sources such as terminal and Github.
#
# That said, one-line expectations in RSpec commonly exceed this limit, and the
# readability is significantly hindered when attempting to break these into
# multiple lines.
#
Layout/LineLength:
  IgnoredPatterns: ['it { should']
  Max: 80

##
# Variable assignment can be indented weirdly, so align to the ending statement
# instead.
#
Layout/CaseIndentation:
  EnforcedStyle: end

##
# Lines can get stupidly long if we indent it to the other params/args.
#
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

##
# Force prettier hash alignment.
#
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

##
# Allow extra spaces when aligning to other operators...
# (doesn't seem to work all the time though)
#
Layout/SpaceAroundOperators:
  AllowForAlignment: true
