inherit_from:
  - _layout.yml
  - _naming.yml
  - _style.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-thread_safety

##
# Merge instead of overwriting. For more details, see:
# https://docs.rubocop.org/rubocop/configuration.html#merging-arrays-using-inherit_mode
#
inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
