inherit_from:
  - _layout.yml
  - _naming.yml
  - _rspec.yml
  - _style.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
