inherit_from:
  - default.yml
  - _rspec.yml

require:
  - rubocop-i18n
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'lib/templates/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

##
# Use Rails I18n instead of GetText.
#
I18n/GetText:
  Enabled: false

##
# Use Rails I18n instead of GetText.
#
I18n/RailsI18n:
  Enabled: true

##
# Translating the specs themselves doesn't make sense.
#
I18n/RailsI18n/DecorateString:
  Exclude:
    - 'spec/**/*'

##
# In the rest of the app, using the logger makes sense. However, it seems to
# not play nicely when generating the seeds, and `puts` is pretty
# straight-forward.
#
Rails/Output:
  Exclude:
    - 'db/seeds/*.rb'
    - 'db/seeds.rb'

##
# This cop makes no sense in the context of migrations.
#
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

##
# This cop makes no sense in the context of migrations.
#
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
